# Generated by Django 4.2.6 on 2023-11-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
