# Generated by Django 4.2.6 on 2023-11-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_skills_jobpost_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('Pełny etat', 'Pełny etat'), ('Połowa etatu', 'Połowa etatu'), ('Ćwierć etatu', 'Ćwierć etatu')], default='Pełny etat', max_length=100),
            preserve_default=False,
        ),
    ]
